name: San Francisco
favicon: null
layout_spectrum: 0.33728
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#071112'
    - '#3b4749'
    - '#ffffff'
    - '#84a0c1'
    - '#01d8e5'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
