name: San Francisco
favicon: null
layout_spectrum: 0.48919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#677ecc'
    - '#030500'
    - '#d2d5da'
    - '#86b1e8'
    - '#cea97c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
